
modLoader="javafml"
loaderVersion="[40,)"
license="LGPLv3"

[[mods]]
modId="molten_metals"
version = "${version}"
displayName="Molten Metals"
logoFile="icon.png"
authors="Ordana, Kayla_the_bee"
itemIcon="molten_metals:template"

description='''
Melt down your metals and cast some ingots!
'''

[[dependencies.molten_metals]] 
    modId="forge" 
    mandatory=true 
    versionRange="[43,)" 
    ordering="NONE"
    side="BOTH"
    
[[dependencies.molten_metals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.molten_metals]]
    modId="moonlight"
    mandatory=true
    versionRange="[1.19.2-2.3.6,]"
    ordering="AFTER"
    side="BOTH"
